#!/usr/bin/env python3
# 한글: SLAM 지도(.yaml+.pgm)의 점유 칸을 벽(직사각형 상자)으로 세운 Gazebo 월드(SDF)를 만든다.
#       지도와 같은 좌표라 AMCL에 같은 지도를 그대로 쓰고, 실기 시험 좌표(A/B 등)를 그대로 쓸 수 있다.
"""
Build a Gazebo Harmonic world (SDF) from a ROS occupancy map (occupied cells -> walls).

Usage: map_to_world.py <map.yaml> <out.sdf> [--height 0.5] [--box X Y SX SY SZ ...]
Occupied cells are merged greedily into rectangles (row runs, then stacked vertically) so the
world has tens of boxes instead of hundreds. The world uses the map frame, so map coordinates
are Gazebo coordinates.
--box adds a static obstacle box (centre X Y in map frame, size SX SY SZ), e.g. the 10 cm test box.
"""
import argparse
import os

import yaml


def read_pgm(path):
    with open(path, 'rb') as f:
        data = f.read()
    # P5 binary PGM: magic, width height, maxval, then bytes (comments allowed)
    tokens, i = [], 0
    while len(tokens) < 4:
        while data[i:i + 1].isspace():
            i += 1
        if data[i:i + 1] == b'#':
            while data[i:i + 1] not in (b'\n', b''):
                i += 1
            continue
        j = i
        while not data[j:j + 1].isspace():
            j += 1
        tokens.append(data[i:j])
        i = j
    if tokens[0] != b'P5':
        raise SystemExit('only binary P5 PGM is supported')
    w, h, maxval = int(tokens[1]), int(tokens[2]), int(tokens[3])
    i += 1
    pix = data[i:i + w * h]
    return w, h, maxval, pix


def occupied_grid(map_yaml):
    meta = yaml.safe_load(open(map_yaml))
    pgm = os.path.join(os.path.dirname(map_yaml), meta['image'])
    w, h, maxval, pix = read_pgm(pgm)
    negate = int(meta.get('negate', 0))
    thr = float(meta.get('occupied_thresh', 0.65))
    occ = [[False] * w for _ in range(h)]
    for row in range(h):          # PGM row 0 = top of the image = max y
        for col in range(w):
            v = pix[row * w + col] / maxval
            p = v if negate else 1.0 - v
            occ[h - 1 - row][col] = p > thr   # occ[y][x] with y up
    return occ, float(meta['resolution']), [float(v) for v in meta['origin'][:2]]


def merge_rectangles(occ):
    """Greedy: horizontal runs per row, then extend each run downwards while identical."""
    h, w = len(occ), len(occ[0])
    used = [[False] * w for _ in range(h)]
    rects = []
    for y in range(h):
        x = 0
        while x < w:
            if not occ[y][x] or used[y][x]:
                x += 1
                continue
            x2 = x
            while x2 + 1 < w and occ[y][x2 + 1] and not used[y][x2 + 1]:
                x2 += 1
            y2 = y
            while y2 + 1 < h and all(occ[y2 + 1][k] and not used[y2 + 1][k]
                                     for k in range(x, x2 + 1)):
                y2 += 1
            for yy in range(y, y2 + 1):
                for xx in range(x, x2 + 1):
                    used[yy][xx] = True
            rects.append((x, y, x2, y2))
            x = x2 + 1
    return rects


def box_link(name, cx, cy, cz, sx, sy, sz, color='0.6 0.6 0.6 1'):
    size = f'<size>{sx:.4f} {sy:.4f} {sz:.4f}</size>'
    return '\n'.join([
        f'      <link name="{name}">',
        f'        <pose>{cx:.4f} {cy:.4f} {cz:.4f} 0 0 0</pose>',
        f'        <collision name="c"><geometry><box>{size}</box></geometry></collision>',
        f'        <visual name="v"><geometry><box>{size}</box></geometry>',
        f'          <material><ambient>{color}</ambient><diffuse>{color}</diffuse></material>',
        '        </visual>',
        '      </link>', ''])


WORLD_HEAD = """<?xml version="1.0"?>
<!-- GENERATED by jetrover_gazebo/scripts/map_to_world.py from {src}
     ({n} occupied cells -> {r} wall boxes, height {h} m). Map frame = world frame. -->
<sdf version="1.9">
  <world name="jetrover_room">
    <physics name="1ms" type="ignored">
      <max_step_size>0.001</max_step_size>
      <real_time_factor>1.0</real_time_factor>
    </physics>
    <plugin filename="gz-sim-physics-system" name="gz::sim::systems::Physics"/>
    <plugin filename="gz-sim-user-commands-system" name="gz::sim::systems::UserCommands"/>
    <plugin filename="gz-sim-scene-broadcaster-system"
            name="gz::sim::systems::SceneBroadcaster"/>
    <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>
    <plugin filename="gz-sim-imu-system" name="gz::sim::systems::Imu"/>
    <light type="directional" name="sun">
      <cast_shadows>true</cast_shadows>
      <pose>0 0 10 0 0 0</pose>
      <diffuse>0.8 0.8 0.8 1</diffuse>
      <specular>0.2 0.2 0.2 1</specular>
      <direction>-0.5 0.1 -0.9</direction>
    </light>
    <model name="ground_plane">
      <static>true</static>
      <link name="link">
        <collision name="c">
          <geometry><plane><normal>0 0 1</normal><size>20 20</size></plane></geometry>
          <surface><friction><ode><mu>1.0</mu><mu2>1.0</mu2></ode></friction></surface>
        </collision>
        <visual name="v">
          <geometry><plane><normal>0 0 1</normal><size>20 20</size></plane></geometry>
          <material><ambient>0.85 0.85 0.8 1</ambient><diffuse>0.85 0.85 0.8 1</diffuse></material>
        </visual>
      </link>
    </model>
    <model name="walls">
      <static>true</static>
"""


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawTextHelpFormatter)
    ap.add_argument('map_yaml')
    ap.add_argument('out_sdf')
    ap.add_argument('--height', type=float, default=0.5)
    ap.add_argument('--box', type=float, nargs=5, action='append', default=[],
                    metavar=('X', 'Y', 'SX', 'SY', 'SZ'))
    args = ap.parse_args()

    occ, res, (ox, oy) = occupied_grid(args.map_yaml)
    rects = merge_rectangles(occ)
    n_cells = sum(sum(r) for r in occ)
    covered = sum((x2 - x + 1) * (y2 - y + 1) for x, y, x2, y2 in rects)
    links = ''.join(
        box_link(f'w{i}', ox + (x + x2 + 1) / 2 * res, oy + (y + y2 + 1) / 2 * res,
                 args.height / 2, (x2 - x + 1) * res, (y2 - y + 1) * res, args.height)
        for i, (x, y, x2, y2) in enumerate(rects))
    boxes = ''.join(
        f'    <model name="obstacle_{i}">\n      <static>true</static>\n'
        + box_link('body', bx, by, sz / 2, sx, sy, sz, '0.8 0.5 0.2 1') + '    </model>\n'
        for i, (bx, by, sx, sy, sz) in enumerate(args.box))
    head = WORLD_HEAD.format(src=os.path.basename(args.map_yaml), n=n_cells, r=len(rects),
                             h=args.height)
    sdf = head + links + '    </model>\n' + boxes + '  </world>\n</sdf>\n'
    open(args.out_sdf, 'w').write(sdf)
    print(f'{n_cells} occupied cells -> {len(rects)} boxes (cover {covered} cells), '
          f'wrote {args.out_sdf}')
    if covered != n_cells:
        raise SystemExit('merge error: covered cells != occupied cells')


if __name__ == '__main__':
    main()
